# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catelogue',
            name='branch',
            field=models.CharField(max_length=30),
        ),
    ]
